name: Publish
on:
  push:
    branches:
      - "main"
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Create Release Candidate or Publish
        id: changesets
        uses: changesets/action@v5
        with:
          publish: pnpm run build